extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: level

  resource/loki:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name,deployment.environment

  batch:
    send_batch_size: 2048
    timeout: 5s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 5m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: ${env:LOKI_PUSH_ENDPOINT}
    default_labels_enabled:
      exporter: false
      job: true
      instance: true

  otlp/tempo:
    endpoint: ${env:TEMPO_OTLP_ENDPOINT}
    tls:
      insecure: ${env:TEMPO_OTLP_INSECURE}

service:
  extensions:
    - health_check

  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlp/tempo

    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - prometheus

    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - attributes/loki
        - resource/loki
        - batch
      exporters:
        - loki
