extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  transform/logs_normalize:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["service_name"], resource.attributes["service.name"]) where attributes["service_name"] == nil and resource.attributes["service.name"] != nil
          - set(attributes["deployment_environment_name"], resource.attributes["deployment.environment.name"]) where attributes["deployment_environment_name"] == nil and resource.attributes["deployment.environment.name"] != nil
          - set(attributes["service_role"], resource.attributes["service.role"]) where attributes["service_role"] == nil and resource.attributes["service.role"] != nil
          - set(attributes["level"], attributes["severity"]) where attributes["level"] == nil and attributes["severity"] != nil
          - set(attributes["level"], attributes["severity_text"]) where attributes["level"] == nil and attributes["severity_text"] != nil

  transform/metrics_scope_labels:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["otel_scope_name"], instrumentation_scope.name) where instrumentation_scope.name != nil

  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: level

  resource/loki:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name,deployment.environment.name,service.role

  batch/default:
    send_batch_size: 2048
    timeout: ${env:CENTRAL_DEFAULT_BATCH_TIMEOUT}

  batch/logs:
    send_batch_size: 128
    timeout: ${env:CENTRAL_LOG_BATCH_TIMEOUT}

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 5m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: ${env:LOKI_PUSH_ENDPOINT}
    default_labels_enabled:
      exporter: false
      job: true
      instance: true

  otlp/tempo:
    endpoint: ${env:TEMPO_OTLP_ENDPOINT}
    tls:
      insecure: ${env:TEMPO_OTLP_INSECURE}

service:
  extensions:
    - health_check

  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch/default
      exporters:
        - otlp/tempo

    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - transform/metrics_scope_labels
        - batch/default
      exporters:
        - prometheus

    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - transform/logs_normalize
        - attributes/loki
        - resource/loki
        - batch/logs
      exporters:
        - loki
